### ISSUE TITLE
Doesn't build with Glib >= 2.36

### ISSUE THREAD

**Issue by fabriceT** [TrilbyWhite/Leela#2]
g_init_type() has been deprecated since version 2.36 of Glib and raise an error while compiling Leela. 

Ref : https://developer.gnome.org/gobject/stable/gobject-Type-Information.html#g-type-init

**Comment by TrilbyWhite** [comment]
Thanks, I had fixed my other glib program, but forgot leela uses it to.  Fixed.

**Comment by fabriceT** [comment]
You're welcome.

Maybe you could add a version check in order make Leela runnable by older versions of GLib.

``` C
if (!GLIB_CHECK_VERSION (2, 36, 0)) 
        g_type_init();
```

But deprecated warnings must not be treated as error anymore. I added `#define GLIB_DISABLE_DEPRECATION_WARNINGS` before the include section to make it happen.
